services:
  face-validator:
    build: .
    container_name: ruteando-validator
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - shared
      
networks:
  shared:
    external: true
    name: ruteando-net
